### PR TITLE
Updated README to include info regarding go modules

### PR DESCRIPTION
**Pull request by Mattie112**
*Issue #, if available:*

*Description of changes:*
- This should make it a bit clearer on how to run this application / example

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sethusrinivasan** [comment]
@Mattie112, Can you please add details on which version of Go you tested these instructions?

**Comment by Mattie112** [comment]
> @Mattie112, Can you please add details on which version of Go you tested these instructions?

Added!

**Comment by sethusrinivasan** [comment]
@Mattie112 , I tried the instructions in recent go version go1.19.3 windows/amd64
looks like the second step that you updated in README needs changes, Can you pls check on your end?

Here are the steps I ran

```
CD C:\github\amazon-timestream-tools\sample_apps_reinvent2021\goV2

C:\github\amazon-timestream-tools\sample_apps_reinvent2021\goV2>go version
go version go1.19.3 windows/amd64

C:\github\amazon-timestream-tools\sample_apps_reinvent2021\goV2>go mod init go_sample
go: creating new go.mod: module go_sample
go: to add module requirements and sums:
        go mod tidy

C:\github\amazon-timestream-tools\sample_apps_reinvent2021\goV2>go get .
go: added github.com/aws/aws-sdk-go v1.44.134
go: added github.com/aws/aws-sdk-go-v2 v1.17.1
go: added github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.4.9
go: added github.com/aws/aws-sdk-go-v2/config v1.17.10
go: added github.com/aws/aws-sdk-go-v2/credentials v1.12.23
go: added github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.19
go: added github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.25
go: added github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.19
go: added github.com/aws/aws-sdk-go-v2/internal/ini v1.3.26
go: added github.com/aws/aws-sdk-go-v2/internal/v4a v1.0.16
go: added github.com/aws/aws-sdk-go-v2/service/iam v1.18.23
go: added github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.10
go: added github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.1.20
go: added github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.7.19
go: added github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.19
go: added github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.13.19
go: added github.com/aws/aws-sdk-go-v2/service/s3 v1.29.1
go: added github.com/aws/aws-sdk-go-v2/service/sns v1.18.3
go: added github.com/aws/aws-sdk-go-v2/service/sqs v1.19.12
go: added github.com/aws/aws-sdk-go-v2/service/sso v1.11.25
go: added github.com/aws/aws-sdk-go-v2/service/ssooidc v1.13.8
go: added github.com/aws/aws-sdk-go-v2/service/sts v1.17.1
go: added github.com/aws/aws-sdk-go-v2/service/timestreamquery v1.14.19
go: added github.com/aws/aws-sdk-go-v2/service/timestreamwrite v1.14.5
go: added github.com/aws/smithy-go v1.13.4
go: added golang.org/x/net v0.2.0
go: added golang.org/x/text v0.4.0


C:\github\amazon-timestream-tools\sample_apps_reinvent2021\goV2>go run crud-ingestion-sample.go
Creating a database with name devops_multi_sample_application
Database with name devops_multi_sample_application successfully created 
...




```

**Comment by Mattie112** [comment]
I always use it that way due to https://go.dev/ref/mod (section `go get`):

```
# Upgrade modules that provide packages imported by packages in the main module.
$ go get -u ./...
```

Might be a difference between Linux and Windows? Will try it out on my Windows PC in the next few days!

(might ofc also be that I don't use it the best way)

edit:
Now that I look at the documentation it might be that `go mod download` is the most logical option to use. https://go.dev/ref/mod#go-mod-download

**Comment by sethusrinivasan** [comment]
Please check recent README.md from resolves the issue you were seeing
1/ https://github.com/awslabs/amazon-timestream-tools/blob/mainline/sample_apps/go/README.md
2/ https://github.com/awslabs/amazon-timestream-tools/blob/mainline/sample_apps/goV2/README.md

**Pull request closed without merging**
